server:
  port: 8082
spring:
  application:
    name: customer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka,http://localhost:8200/eureka
    register-with-eureka: true
    fetch-registry: true