#服务端口号
server:
  port: 8100
#服务名称（serviceid）
spring:
  application:
    name: springcloud-eureka
eureka:
  #注册中心ip地址
  instance:
    hostname: 127.0.0.1
  client:
    #客户端调用地址
    serviceUrl:
      defaultZone: http://localhost:8200/eureka/
    #因为自己为注册中心，不注册自己（集群需要为true，你中有我，我中有你思想）
    register-with-eureka: true
    #因为自己是注册中心，不去在应用中检测服务（集群需要为true，你中有我，我中有你思想）
    fetch-registry: true
