server:
  port: 8200
spring:
  application:
    name: springcloud-eureka
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
    register-with-eureka: true
    fetch-registry: true