server:
  port: 8083
#服务名称（注册到eureka的名称，serviceid）
spring:
  application:
    name: provider
eureka:
  client:
    #注册到eureka的地址
    service-url:
      defaultZone: http://localhost:8100/eureka
    #把自己注册到注册中心中
    register-with-eureka: true
    #需要从eureka上获取注册信息
    fetch-registry: true
